#pragma once
#include "CoreMinimal.h"
#include "EBadNameConditionSubType.generated.h"

UENUM(BlueprintType)
enum class EBadNameConditionSubType : uint8 {
    MT_None,
    MT_BattleTime1,
    MT_BattleTime2,
    MT_MaxSpeed,
    MT_TotalCP,
    MT_LostCP,
    MT_HighestWinningStreak,
    MT_AverageContactNumber1,
    MT_AverageWallContact1,
    MT_WinRate,
    MT_AverageContactNumber2,
    MT_AverageWallContact2,
    MT_TotalDistanceTraveled,
    MT_IncarnationOfHighway,
    MT_LegendaryScribbler,
    MT_MrPerfect,
    MT_UltimateUnsinkableShip,
    MT_TheRuler,
    MT_GuardianGod,
    MT_TheFourHeavenlyKings,
    MT_TheFourGods,
    MT_DriverOfCarModel,
    MT_RidersOfTheCar,
    MT_PA_Resident,
    MT_PA_Regulars,
    MT_ForOnePerson,
    MT_HalfMan,
    MT_OilTycoon,
    MT_Spendthrift,
    MT_TuneMastersSponsor,
    MT_MasterTunesClient,
    MT_TunersMavens,
    MT_OutlawWhoBreaksTheLaw,
    MT_LoveAndPeace,
    MT_OnTheRoadTraining,
    MT_Loser,
    MT_Sokushinbutsu,
    MT_UFO,
    MT_BariBari,
    MT_FirstOftheWeek,
    MT_MidWeek,
    MT_Friday,
    MT_OnTheWeekend,
    MT_TheObsessiveChaser,
    MT_Tourists,
    MT_RivalTeams,
    MT_LoserToSpecialRivals,
    MT_WinsSpecialRivals_01,
    MT_WinsSpecialRivals_02,
    MT_WinsSpecialRivals_03,
    MT_Num,
    MT_Condition03_Top = MT_IncarnationOfHighway,
    MT_Condition03_End = MT_Tourists,
};

