#pragma once
#include "CoreMinimal.h"
#include "EBGMType.generated.h"

UENUM(BlueprintType)
enum class EBGMType : uint8 {
    Jamminin_The_Garage,
    Hunter,
    Vampire_Killer,
    Night_Fly_Remix,
    BigApple_remix,
    MS_BGM_BossBatlle,
    MS_BGM_BossPassing,
    MS_BGM_Dealer,
    MS_BGM_FreeRunC1,
    MS_BGM_FreeRunCM,
    MS_BGM_GarageFriday,
    MS_BGM_GarageMonday,
    MS_BGM_GarageResult,
    MS_BGM_GarageSaturday,
    MS_BGM_GarageSunday,
    MS_BGM_GarageThursday,
    MS_BGM_GarageTuesday,
    MS_BGM_GarageWednesday,
    MS_BGM_LastBossPassing,
    MS_BGM_PA,
    MS_BGM_PassingBatlle,
    MS_BGM_SecretBossBatlle,
    MS_BGM_SecretBossPassing,
    MS_BGM_TL_Batlle,
    MS_BGM_TL_Passing,
    MS_BGM_TM_Passing,
    MS_BGM_TM_Stage1,
    MS_BGM_TM_Stage2,
    MS_BGM_TM_Stage3,
    MS_BGM_WandererPassing,
    MS_BGM_FreeRunCS,
    MS_BGM_Replay,
    MS_BGM_LastBossBatlle,
    MS_BGM_Title,
    MS_BGM_Collection,
    MS_BGM_Reference,
    MS_BGM_Perk,
    MS_BGM_Garage,
    MS_BGM_Tune,
    MS_BGM_Setting,
    MS_BGM_Aero,
    MS_BGM_Livery,
    MS_BGM_Option,
    MS_BGM_CourseIn,
    MS_BGM_Conversation,
    None,
};

