#pragma once
#include "CoreMinimal.h"
#include "ECourseAssistType.generated.h"

UENUM(BlueprintType)
enum class ECourseAssistType : uint8 {
    None,
    InnerCircularRouteInbound,
    InnerCircularRouteOutbound,
    MukojimaLineInbound,
    MukojimaLineOutbound,
    FukagawaLineInbound,
    FukagawaLineOutbound,
    DaibaLineInbound,
    DaibaLineOutbound,
    BayShoreRouteInbound,
    BayShoreRouteOutbound,
    DaikokuLineInbound,
    DaikokuLineOutbound,
    YokohaneLineInbound,
    YokohaneLineOutbound,
    HanedaLineInbound,
    HanedaLineOutbound,
    HW_C1_Takarachou,
    HW_C1_Kyobashi,
    HW_C1_Shintomichou,
    HW_C1_Ginza,
    HW_C1_Shiodome,
    HW_C1_Shibakouen,
    HW_C1_Iikura,
    HW_C1_Kasumigaseki,
    HW_C1_Daikanchou,
    HW_C1_Kitanomaru,
    HW_C1_Kandabashi,
    HW_C1_Gofukubashi,
    HW_C1_Edobashi,
    PA_9_Tatsumi1_Exit,
    PA_9_Tatsumi2_Exit,
    PA_11_Shibaura_Exit,
    PA_B_Ichikawa_Exit,
    PA_B_Oi_Westbound_Exit,
    PA_B_Oi_Eastbound_Exit,
    PA_B_Daikoku_Exit,
    PA_9_Hakozaki_Exit,
    PA_9_Tatsumi_Exit,
    PA_1_HeiwajimaUp_Exit,
    PA_1_HeiwajimaDown_Exit,
    Num,
};

