#pragma once
#include "CoreMinimal.h"
#include "ECourseEnter.generated.h"

UENUM(BlueprintType)
enum class ECourseEnter : uint8 {
    HW_C1_Ginza_Inner,
    HW_C1_Ginza_Outer,
    HW_C1_Shibakouen_Inner,
    HW_C1_Shibakouen_Outer,
    HW_C1_Kasumigaseki_Inner,
    HW_C1_Kasumigaseki_Outer,
    HW_C1_Kandabashi_Inner,
    HW_C1_Kandabashi_Outer,
    PA_9_Hakozaki_Outbound_Exit,
    PA_6_Hakozaki_Inbound_Exit,
    HW_9_Kiba_Inbound,
    HW_9_Fukuzumi_Outbound,
    PA_11_Shibaura_Inbound_Exit,
    HW_B_Rinkaihukutoshin_Westbound,
    HW_B_Ariake_Eastbound,
    HW_B_KukoChuo_Westbound,
    HW_B_KukoChuo_Eastbound,
    PA_B_Daikoku_Eastbound_Exit,
    PA_1_Daikoku_Inbound_Exit,
    HW_K_Shioiri_Inbound,
    HW_K_Adada_Outbound,
    PA_1_Heiwajima_Inbound_Exit,
    PA_1_Heiwajima_Outbound_Exit,
    PA_9_Tatsumi_Inbound_Exit,
    HW_9_Shiohama_Outbound,
    HW_B_Shinkiba_Westbound,
    HW_B_Oiminami_Westbound,
    HW_B_Ukishima_Westbound,
    HW_B_Higashiogishima_Westbound,
    HW_B_Oi_Eastbound,
    HW_B_Chukanoiminami_Eastbound,
    HW_B_Ukishima_Eastbound,
    HW_B_Higashiogishima_Eastbound,
    HW_11_Daiba_Inbound,
    HW_1_Shibaura_Outbound,
    HW_1_katsushima_Outbound,
    HW_1_Haneda_Outbound,
    HW_1_Shibaura_Inbound,
    HW_1_katsushima_Inbound,
    HW_1_Haneda_Inbound,
    HW_K_Hamakawasaki_Outbound,
    HW_K_Hamakawasaki_Inbound,
    HW_K_Namamugi_Inbound,
    Num,
    None,
};

