#pragma once
#include "CoreMinimal.h"
#include "ESkillTreeType.generated.h"

UENUM(BlueprintType)
enum class ESkillTreeType : uint8 {
    STT_NEW_WALLET,
    STT_ATTACK,
    STT_DEFENCE,
    STT_WALL_SHOCK_ABSORPTION,
    STT_CAR_SHOCK_ABSORPTION,
    STT_MAINTENANCE_EXPERT,
    STT_LOYAL_CUSTOMERS,
    STT_NEGOTIATION,
    STT_WINE_OF_VICTORY,
    STT_BATTLE_TECHNIQUES,
    STT_RUN_TECHNIQUES,
    STT_RUNNNR,
    STT_SP,
    STT_GARAGE_EXTENSION,
    STT_PA_CAMERAMAN,
    STT_PROVEN_EXPERIENCE,
    STT_UNLOCK_TUNE,
    STT_UNLOCK_MACHINE,
    STT_ENGINE_REPLACEMENT,
    STT_BOUNTY_HUNTER,
    STT_CRUISING_ENTHUSIASTS,
    STT_TIRE_CONSERVATION,
    STT_HELLS_EARS,
    STT_AURA,
    STT_HEART_FIRED_BY_ADVERSITY,
    STT_DO_NOT_BE_HASTY,
    STT_THICK_BACK,
    STT_SHORT_SHOWDOWN,
    STT_ENDURANCE_BATTLE,
    STT_MIDNIGHT_HIGHWAY,
    STT_BATTLE_IS_YET_TO_COME,
    Num,
    STT_NONE,
};

