#pragma once
#include "CoreMinimal.h"
#include "EUserInfoCommand.generated.h"

UENUM(BlueprintType)
enum class EUserInfoCommand : uint8 {
    AddCp,
    AddCpFull,
    SetUpperLimitCp,
    AddBp,
    SetMaxGarageMyCarNum,
    SetTunePartsOpen,
    SetTunePartsOpenAll,
    SetFullTuneTheSelectedCar,
    SetMilageTheSelectedCar,
    AddBuyableCar,
    AddBuyableCarAll,
    FullReplicateSelectMyCar,
    AddBuyableEngine,
    AddBuyableEngineAll,
    AddCarIntoGarage,
    AddCarIntoGarageFill,
    AddVinylSticker,
    AddVinylStickerAll,
    AddLiverySticker,
    AddLiveryStickerAll,
    SetRivalSituation,
    SetRivalSituationBySerial,
    AddForcedAppearanceRival,
    ClearForcedAppearanceRivals,
    SetTutorialMode,
    SetStoryStage,
    SetObjectiveClearPreset,
    SetObjectiveClear,
    SetPAConversation,
    SetVersion,
    AdvanceDay,
    AdvanceTimeZone,
    UnlockCourseArea,
    UnlockEntrance,
    UnlockEntranceAll,
    UnlockParkingArea,
    UnlockParkingAreaAll,
    SetBattleNum,
    SetWinNum,
    SetLoseNum,
    SetDrawNum,
    SetWiningStreak,
    SetLosingStreak,
    SetMaxSpeed,
    SetTotalMilage,
    SetNumOfVisitParkingArea,
    SetNumOfEntriesByCar,
    SetNumOfMetTuner,
    SetNumOfTunedByTuner,
    AddBadnameHistory,
    AddBadnameHistoryAll,
    AddPerk,
    AddPerkAll,
    RemovePerkAll,
    AddLiveryAura,
    AddLiveryAuraAll,
    Num,
};

